### ISSUE TITLE
Intermittent errors running specs locally

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#290]
I've gotten the type of error listed below twice and then it goes away if I re-run the specs.  I don't see the seed listed, so I'm not sure how to reproduce the run that triggered the error.

Step one is probably to tell me where to look for the seed in the test output.

```text
  1) Importer::ModsImporter#import an Image creates a new image, files, and a collection
     Failure/Error: image = importer.import(file)
     SPARQL::Client::MalformedQuery:
       {"trace":"org.apache.marmotta.platform.core.exception.MarmottaException: error while evaluating query \n\tat org.apache.marmotta.platform.sparql.services.sparql.SparqlServiceImpl$5.call(SparqlServiceImpl.java:311)\n\tat org.apache.marmotta.platform.sparql.services.sparql.SparqlServiceImpl$5.call(SparqlServiceImpl.java:279)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\tat java.lang.Thread.run(Thread.java:745)\nCaused by: org.openrdf.query.QueryEvaluationException: org.h2.jdbc.JdbcSQLException: General error: \"java.lang.IllegalStateException: Transaction is closed [1.4.178/4]\"; SQL statement:\nSELECT id,ntype,svalue,ivalue,dvalue,tvalue,tzoffset,bvalue,lang,ltype,createdAt FROM nodes WHERE id IN(?,?) LIMIT 2 [50000-178]\n\tat org.openrdf.repository.sail.SailGraphQuery.evaluate(SailGraphQuery.java:106)\n\tat org.apache.marmotta.platform.sparql.services.sparql.SparqlServiceImpl.query(SparqlServiceImpl.java:372)\n\tat org.apache.marmotta.platform.sparql.services.sparql.SparqlServiceImpl.query(SparqlServiceImpl.java:367)\n\tat org.apache.marmotta.platform.sparql.services.sparql.SparqlServiceImpl.access$900(SparqlServiceImpl.java:60)\n\tat org.apache.marmotta.platform.sparql.services.sparql.SparqlServiceImpl$5.call(SparqlServiceImpl.java:294)\n\t... 5 more\nCaused by: org.openrdf.sail.SailException: org.h2.jdbc.JdbcSQLException: General error: \"java.lang.IllegalStateException: Transaction is closed [1.4.178/4]\"; SQL statement:\nSELECT id,ntype,svalue,ivalue,dvalue,tvalue,tzoffset,bvalue,lang,ltype,createdAt FROM nodes WHERE id IN(?,?) LIMIT 2 [50000-178]\n\tat org.apache.marmotta.kiwi.sparql.sail.KiWiSparqlSailConnection.evaluate(KiWiSparqlSailConnection.java:100)\n\tat org.openrdf.sail.helpers.SailConnectionWrapper.evaluate(SailConnectionWrapper.java:95)\n\tat org.openrdf.sail.helpers.SailConnectionWrapper.evaluate(SailConnectionWrapper.java:95)\n\tat org.openrdf.repository.sail.SailGraphQuery.evaluate(SailGraphQuery.java:64)\n\t... 9 more\nCaused by: org.openrdf.query.QueryEvaluationException: org.h2.jdbc.JdbcSQLException: General error: \"java.lang.IllegalStateException: Transaction is closed [1.4.178/4]\"; SQL statement:\nSELECT id,ntype,svalue,ivalue,dvalue,tvalue,tzoffset,bvalue,lang,ltype,createdAt FROM nodes WHERE id IN(?,?) LIMIT 2 [50000-178]\n\tat org.apache.marmotta.kiwi.sparql.evaluation.KiWiEvaluationStrategy.evaluateNative(KiWiEvaluationStrategy.java:404)\n\tat org.apache.marmotta.kiwi.sparql.evaluation.KiWiEvaluationStrategy.evaluate(KiWiEvaluationStrategy.java:125)\n\tat org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:592)\n\tat org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:197)\n\tat org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:662)\n\tat org.apache.marmotta.kiwi.sparql.evaluation.KiWiEvaluationStrategy.evaluate(KiWiEvaluationStrategy.java:109)\n\tat org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:577)\n\tat org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:197)\n\tat org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:607)\n\tat org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:197)\n\tat org.apache.marmotta.kiwi.sparql.sail.KiWiSparqlSailConnection.evaluate(KiWiSparqlSailConnection.java:97)\n\t... 12 more\nCaused by: org.h2.jdbc.JdbcSQLException: General error: \"java.lang.IllegalStateException: Transaction is closed [1.4.178/4]\"; SQL statement:\nSELECT id,ntype,svalue,ivalue,dvalue,tvalue,tzoffset,bvalue,lang,ltype,createdAt FROM nodes WHERE id IN(?,?) LIMIT 2 [50000-178]\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:344)\n\tat org.h2.message.DbException.get(DbException.java:167)\n\tat org.h2.message.DbException.convert(DbException.java:294)\n\tat org.h2.command.Command.executeQuery(Command.java:209)\n\tat org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:109)\n\tat org.apache.marmotta.kiwi.persistence.KiWiConnection.loadNodesByIds(KiWiConnection.java:496)\n\tat org.apache.marmotta.kiwi.sparql.evaluation.KiWiEvaluationStrategy$2.apply(KiWiEvaluationStrategy.java:250)\n\tat org.apache.marmotta.kiwi.sparql.evaluation.KiWiEvaluationStrategy$2.apply(KiWiEvaluationStrategy.java:236)\n\tat org.apache.marmotta.kiwi.persistence.util.ResultSetIteration.next(ResultSetIteration.java:115)\n\tat info.aduna.iteration.Iterations.addAll(Iterations.java:83)\n\tat info.aduna.iteration.Iterations.asList(Iterations.java:44)\n\tat org.apache.marmotta.kiwi.sparql.evaluation.KiWiEvaluationStrategy.evaluateNative(KiWiEvaluationStrategy.java:379)\n\t... 22 more\nCaused by: java.lang.IllegalStateException: Transaction is closed [1.4.178/4]\n\tat org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:757)\n\tat org.h2.mvstore.db.TransactionStore$Transaction.checkNotClosed(TransactionStore.java:808)\n\tat org.h2.mvstore.db.TransactionStore$TransactionMap.get(TransactionStore.java:1165)\n\tat org.h2.mvstore.db.TransactionStore$TransactionMap.get(TransactionStore.java:1133)\n\tat org.h2.mvstore.db.TransactionStore$TransactionMap.containsKey(TransactionStore.java:1153)\n\tat org.h2.mvstore.db.TransactionStore$TransactionMap$2.fetchNext(TransactionStore.java:1468)\n\tat org.h2.mvstore.db.TransactionStore$TransactionMap$2.next(TransactionStore.java:1483)\n\tat org.h2.mvstore.db.MVSecondaryIndex$MVStoreCursor.next(MVSecondaryIndex.java:509)\n\tat org.h2.index.IndexCursor.next(IndexCursor.java:278)\n\tat org.h2.table.TableFilter.next(TableFilter.java:361)\n\tat org.h2.command.dml.Select.queryFlat(Select.java:533)\n\tat org.h2.command.dml.Select.queryWithoutCache(Select.java:646)\n\tat org.h2.command.dml.Query.query(Query.java:323)\n\tat org.h2.command.dml.Query.query(Query.java:291)\n\tat org.h2.command.dml.Query.query(Query.java:37)\n\tat org.h2.command.CommandContainer.query(CommandContainer.java:91)\n\tat org.h2.command.Command.executeQuery(Command.java:197)\n\t... 30 more\n","type":"MarmottaException","message":"error while evaluating query "} Processing query CONSTRUCT { <http://id.loc.gov/vocabulary/preservation/copyrightStatus/unk> ?g70133312651920 ?g70133312651720 . } WHERE { <http://id.loc.gov/vocabulary/preservation/copyrightStatus/unk> ?g70133312651920 ?g70133312651720 . }
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/sparql-client-1.1.5/lib/sparql/client.rb:345:in `block in response'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/sparql-client-1.1.5/lib/sparql/client.rb:686:in `call'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/sparql-client-1.1.5/lib/sparql/client.rb:686:in `block in request'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/sparql-client-1.1.5/lib/sparql/client.rb:682:in `times'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/sparql-client-1.1.5/lib/sparql/client.rb:682:in `request'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/rdf-marmotta-0.0.8/lib/rdf/marmotta.rb:84:in `request'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/sparql-client-1.1.5/lib/sparql/client.rb:342:in `response'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/sparql-client-1.1.5/lib/sparql/client.rb:303:in `query'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/sparql-client-1.1.5/lib/sparql/client.rb:269:in `block in call_query_method'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/sparql-client-1.1.5/lib/sparql/client/query.rb:312:in `result'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/sparql-client-1.1.5/lib/sparql/client/query.rb:296:in `each_statement'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/sparql-client-1.1.5/lib/sparql/client/repository.rb:250:in `query_pattern'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/rdf-1.1.14/lib/rdf/mixin/queryable.rb:301:in `block in enum_for'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/rdf-1.1.14/lib/rdf/mixin/enumerable.rb:158:in `each'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/rdf-1.1.14/lib/rdf/mixin/enumerable.rb:158:in `each'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/rdf-1.1.14/lib/rdf/mixin/enumerable.rb:158:in `each_statement'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/rdf-1.1.14/lib/rdf/mixin/writable.rb:129:in `insert_statements'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/rdf-1.1.14/lib/rdf/mixin/writable.rb:32:in `<<'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/rdf-1.1.14/lib/rdf/mixin/mutable.rb:71:in `<<'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/bundler/gems/ActiveTriples-f925f2ae1c84/lib/active_triples/rdf_source.rb:306:in `reload'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/bundler/gems/ActiveTriples-f925f2ae1c84/lib/active_triples/rdf_source.rb:580:in `block in from_uri'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/bundler/gems/ActiveTriples-f925f2ae1c84/lib/active_triples/rdf_source.rb:579:in `tap'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/bundler/gems/ActiveTriples-f925f2ae1c84/lib/active_triples/rdf_source.rb:579:in `from_uri'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/bundler/gems/ActiveTriples-f925f2ae1c84/lib/active_triples/relation.rb:185:in `make_node'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/bundler/gems/ActiveTriples-f925f2ae1c84/lib/active_triples/relation.rb:169:in `convert_object'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/bundler/gems/ActiveTriples-f925f2ae1c84/lib/active_triples/relation.rb:43:in `block in result'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/rdf-1.1.14/lib/rdf/mixin/queryable.rb:301:in `<<'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/rdf-1.1.14/lib/rdf/mixin/queryable.rb:301:in `block (2 levels) in enum_for'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/rdf-1.1.14/lib/rdf/repository.rb:341:in `call'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/rdf-1.1.14/lib/rdf/repository.rb:341:in `block (4 levels) in query_pattern'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/rdf-1.1.14/lib/rdf/repository.rb:339:in `each'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/rdf-1.1.14/lib/rdf/repository.rb:339:in `block (3 levels) in query_pattern'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/rdf-1.1.14/lib/rdf/repository.rb:336:in `each'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/rdf-1.1.14/lib/rdf/repository.rb:336:in `block (2 levels) in query_pattern'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/rdf-1.1.14/lib/rdf/repository.rb:333:in `each'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/rdf-1.1.14/lib/rdf/repository.rb:333:in `block in query_pattern'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/rdf-1.1.14/lib/rdf/repository.rb:330:in `each'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/rdf-1.1.14/lib/rdf/repository.rb:330:in `query_pattern'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/rdf-1.1.14/lib/rdf/mixin/queryable.rb:85:in `query'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/rdf-1.1.14/lib/rdf/model/graph.rb:242:in `each'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/bundler/gems/ActiveTriples-f925f2ae1c84/lib/active_triples/rdf_source.rb:81:in `each'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/rdf-1.1.14/lib/rdf/mixin/queryable.rb:149:in `grep'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/rdf-1.1.14/lib/rdf/mixin/queryable.rb:149:in `query_pattern'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/rdf-1.1.14/lib/rdf/mixin/queryable.rb:301:in `block in enum_for'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/bundler/gems/ActiveTriples-f925f2ae1c84/lib/active_triples/relation.rb:42:in `each'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/bundler/gems/ActiveTriples-f925f2ae1c84/lib/active_triples/relation.rb:42:in `each_with_object'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/bundler/gems/ActiveTriples-f925f2ae1c84/lib/active_triples/relation.rb:42:in `result'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/bundler/gems/ActiveTriples-f925f2ae1c84/lib/active_triples/relation.rb:20:in `respond_to?'
     # ./app/models/image.rb:21:in `Array'
     # ./app/models/image.rb:21:in `[]'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/active-fedora-9.2.0.rc1/lib/active_fedora/attributes.rb:33:in `block in attributes'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/active-fedora-9.2.0.rc1/lib/active_fedora/attributes.rb:33:in `each'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/active-fedora-9.2.0.rc1/lib/active_fedora/attributes.rb:33:in `each_with_object'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/active-fedora-9.2.0.rc1/lib/active_fedora/attributes.rb:33:in `attributes'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/activemodel-4.2.3/lib/active_model/serialization.rb:100:in `serializable_hash'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/active-fedora-9.2.0.rc1/lib/active_fedora/serialization.rb:16:in `serializable_hash'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/active-fedora-9.2.0.rc1/lib/active_fedora/profile_indexing_service.rb:8:in `export'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/active-fedora-9.2.0.rc1/lib/active_fedora/indexing_service.rb:35:in `generate_solr_document'
     # ./app/services/image_indexer.rb:24:in `generate_solr_document'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/active-fedora-9.2.0.rc1/lib/active_fedora/indexing.rb:15:in `to_solr'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/active-fedora-9.2.0.rc1/lib/active_fedora/indexing.rb:24:in `update_index'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/active-fedora-9.2.0.rc1/lib/active_fedora/indexing.rb:46:in `create_record'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/active-fedora-9.2.0.rc1/lib/active_fedora/callbacks.rb:237:in `block (2 levels) in create_record'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:553:in `block (2 levels) in compile'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:88:in `run_callbacks'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/active-fedora-9.2.0.rc1/lib/active_fedora/callbacks.rb:237:in `block in create_record'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:553:in `block (2 levels) in compile'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:88:in `run_callbacks'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/active-fedora-9.2.0.rc1/lib/active_fedora/callbacks.rb:236:in `create_record'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/active-fedora-9.2.0.rc1/lib/active_fedora/persistence.rb:139:in `create_or_update'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/active-fedora-9.2.0.rc1/lib/active_fedora/persistence.rb:31:in `save!'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/active-fedora-9.2.0.rc1/lib/active_fedora/validations.rb:56:in `save!'
     # ./lib/importer/factory/object_factory.rb:53:in `block in create'
     # /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/active-fedora-9.2.0.rc1/lib/active_fedora/core.rb:36:in `initialize'
     # ./lib/importer/factory/object_factory.rb:52:in `new'
     # ./lib/importer/factory/object_factory.rb:52:in `create'
     # ./lib/importer/factory/object_factory.rb:15:in `run'
     # ./lib/importer/mods_importer.rb:32:in `create_fedora_objects'
     # ./lib/importer/mods_importer.rb:23:in `import'
     # ./spec/importer/mods_importer_spec.rb:36:in `block (4 levels) in <top (required)>'
     # ./spec/importer/mods_importer_spec.rb:35:in `block (3 levels) in <top (required)>'

```

**Comment by jcoyne** [comment]
It looks like you have Marmotta running on h2 instead of postgresql. The instructions (https://github.com/curationexperts/alexandria-v2/#set-up-marmotta) say to use postgresql.
