### ISSUE TITLE
ETD Import failing

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#297]
Sample file 004511577.xml

commit 789ddeb8f0e1f824dca4d0d0f5d4d057d7cb326f (current head of master)

```text
$ bundle exec traject -c traject_config.rb tmp/download_root/marc/004511577.xml
Performance on MRI may be improved with the concurrent-ruby-ext gem. Please see http://concurrent-ruby.com
/Users/mark/Documents/workspace/_no_backup/RubymineProjects/alexandria-v2/app/models/concerns/relators.rb:2: warning: already initialized constant Metadata::MARCREL
/Users/mark/Documents/workspace/_no_backup/RubymineProjects/alexandria-v2/app/models/concerns/relators.rb:2: warning: previous definition of MARCREL was here
2015-07-08T00:40:11-05:00  INFO traject (2.0.2) executing with: `-c traject_config.rb tmp/download_root/marc/004511577.xml`
2015-07-08T00:40:11-05:00  INFO Reading from tmp/download_root/marc/004511577.xml
2015-07-08T00:40:11-05:00  INFO    Indexer with 1 processing threads, reader: Traject::MarcReader and writer: ObjectFactoryWriter
filedir set
looking for FloresFernandez_ucsb_0035D_12167.pdf
Done with save
  Created collection fk/46/d6/1z/fk46d61z7d (etds)
done with save of #<Collection:0x007ffd7fdb2520>, now yielding (true)
done with yield, leaving run of #<Importer::Factory::CollectionFactory:0x007ffd78b939f8>
2015-07-08T00:40:18-05:00 FATAL Traject::CommandLine: Unexpected exception, terminating execution: #<NoMethodError: undefined method `first' for nil:NilClass>
/Users/mark/Documents/workspace/_no_backup/RubymineProjects/alexandria-v2/lib/importer/factory/etd_factory.rb:41:in `log_created': undefined method `first' for nil:NilClass (NoMethodError)
	from /Users/mark/Documents/workspace/_no_backup/RubymineProjects/alexandria-v2/lib/importer/factory/object_factory.rb:62:in `block in create'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/active-fedora-9.2.0.rc1/lib/active_fedora/core.rb:36:in `initialize'
	from /Users/mark/Documents/workspace/_no_backup/RubymineProjects/alexandria-v2/lib/importer/factory/object_factory.rb:54:in `new'
	from /Users/mark/Documents/workspace/_no_backup/RubymineProjects/alexandria-v2/lib/importer/factory/object_factory.rb:54:in `create'
	from /Users/mark/Documents/workspace/_no_backup/RubymineProjects/alexandria-v2/lib/importer/factory/object_factory.rb:15:in `run'
	from /Users/mark/Documents/workspace/_no_backup/RubymineProjects/alexandria-v2/lib/object_factory_writer.rb:60:in `put'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/traject-2.0.2/lib/traject/indexer.rb:364:in `block (2 levels) in process'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/traject-2.0.2/lib/traject/thread_pool.rb:110:in `block in maybe_in_thread_pool'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/concurrent-ruby-0.8.0/lib/concurrent/executor/ruby_thread_pool_worker.rb:62:in `call'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/concurrent-ruby-0.8.0/lib/concurrent/executor/ruby_thread_pool_worker.rb:62:in `block in run'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/concurrent-ruby-0.8.0/lib/concurrent/executor/ruby_thread_pool_worker.rb:53:in `loop'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/concurrent-ruby-0.8.0/lib/concurrent/executor/ruby_thread_pool_worker.rb:53:in `run'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/concurrent-ruby-0.8.0/lib/concurrent/executor/ruby_thread_pool_executor.rb:255:in `block in create_worker_thread'
```

**Comment by jcoyne** [comment]
Fixed in #295
