### ISSUE TITLE
etd import error

### ISSUE THREAD

**Issue by acozine** [curationexperts/alexandria-v2#343]
When importing an ETD with no supplemental files, the importer errors out. Stacktrace:
```
2015-07-22T20:00:20+00:00 FATAL Traject::CommandLine: Unexpected exception, terminating execution: #<TypeError: no implicit conversion of nil into Array>
/opt/alex2/releases/20150722194038/app/services/attach_files_to_etd.rb:24:in `+': no implicit conversion of nil into Array (TypeError)
	from /opt/alex2/releases/20150722194038/app/services/attach_files_to_etd.rb:24:in `block in run'
	from /usr/local/lib/ruby/2.2.0/tmpdir.rb:88:in `mktmpdir'
	from /opt/alex2/releases/20150722194038/app/services/attach_files_to_etd.rb:15:in `run'
	from /opt/alex2/releases/20150722194038/app/services/attach_files_to_etd.rb:4:in `run'
	from /opt/alex2/releases/20150722194038/lib/importer/factory/etd_factory.rb:20:in `after_create'
	from /opt/alex2/releases/20150722194038/lib/importer/factory/object_factory.rb:58:in `block in create'
	from /opt/alex2/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-223391b31c55/lib/active_fedora/core.rb:36:in `initialize'
	from /opt/alex2/releases/20150722194038/lib/importer/factory/object_factory.rb:56:in `new'
	from /opt/alex2/releases/20150722194038/lib/importer/factory/object_factory.rb:56:in `create'
	from /opt/alex2/releases/20150722194038/lib/importer/factory/object_factory.rb:15:in `run'
	from /opt/alex2/releases/20150722194038/lib/object_factory_writer.rb:70:in `build_object'
	from /opt/alex2/releases/20150722194038/lib/object_factory_writer.rb:64:in `put'
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/traject-2.1.0/lib/traject/indexer.rb:438:in `block (2 levels) in process'
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/traject-2.1.0/lib/traject/thread_pool.rb:110:in `block in maybe_in_thread_pool'
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/concurrent-ruby-0.8.0/lib/concurrent/executor/ruby_thread_pool_worker.rb:62:in `call'
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/concurrent-ruby-0.8.0/lib/concurrent/executor/ruby_thread_pool_worker.rb:62:in `block in run'
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/concurrent-ruby-0.8.0/lib/concurrent/executor/ruby_thread_pool_worker.rb:53:in `loop'
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/concurrent-ruby-0.8.0/lib/concurrent/executor/ruby_thread_pool_worker.rb:53:in `run'
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/concurrent-ruby-0.8.0/lib/concurrent/executor/ruby_thread_pool_executor.rb:255:in `block in create_worker_thread'
```

**Comment by acozine** [comment]
This appears to be fixed by c48fb50 - ETDs with no supplemental files now give the same errors as those with supplemental files - see #344
