### ISSUE TITLE
MARC Import Error - ArgumentError: invalid date

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#354]
Occurs on the first import run for 004511961.xml, runs cleanly if you re-run the import.

```
$ RAILS_ENV=production bundle exec traject -c traject_config.rb /opt/download_root/marc/004511961.xml
Performance on MRI may be improved with the concurrent-ruby-ext gem. Please see http://concurrent-ruby.com
2015-07-23T15:29:00+00:00  INFO traject (2.1.0) executing with: `-c traject_config.rb /opt/download_root/marc/004511961.xml`
2015-07-23T15:29:00+00:00  INFO Reading from /opt/download_root/marc/004511961.xml
2015-07-23T15:29:00+00:00  INFO    Indexer with 1 processing threads, reader: Traject::MarcReader and writer: ObjectFactoryWriter
2015-07-23T15:29:02+00:00 FATAL Traject::CommandLine: Unexpected exception, terminating execution: #<ArgumentError: invalid date>
/opt/alex2/releases/20150722223719/app/services/update_metadata_from_proquest_file.rb:38:in `parse': invalid date (ArgumentError)
	from /opt/alex2/releases/20150722223719/app/services/update_metadata_from_proquest_file.rb:38:in `embargo_release_date'
	from /opt/alex2/releases/20150722223719/app/services/update_metadata_from_proquest_file.rb:94:in `no_embargo?'
	from /opt/alex2/releases/20150722223719/app/services/update_metadata_from_proquest_file.rb:74:in `update_embargo_metadata!'
	from /opt/alex2/releases/20150722223719/app/services/update_metadata_from_proquest_file.rb:23:in `run'
	from /opt/alex2/releases/20150722223719/app/services/attach_files_to_etd.rb:21:in `block in run'
	from /usr/local/lib/ruby/2.2.0/tmpdir.rb:88:in `mktmpdir'
	from /opt/alex2/releases/20150722223719/app/services/attach_files_to_etd.rb:15:in `run'
	from /opt/alex2/releases/20150722223719/app/services/attach_files_to_etd.rb:4:in `run'
	from /opt/alex2/releases/20150722223719/lib/importer/factory/etd_factory.rb:20:in `after_create'
	from /opt/alex2/releases/20150722223719/lib/importer/factory/object_factory.rb:58:in `block in create'
	from /opt/alex2/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-223391b31c55/lib/active_fedora/core.rb:36:in `initialize'
	from /opt/alex2/releases/20150722223719/lib/importer/factory/object_factory.rb:56:in `new'
	from /opt/alex2/releases/20150722223719/lib/importer/factory/object_factory.rb:56:in `create'
	from /opt/alex2/releases/20150722223719/lib/importer/factory/object_factory.rb:15:in `run'
	from /opt/alex2/releases/20150722223719/lib/object_factory_writer.rb:70:in `build_object'
	from /opt/alex2/releases/20150722223719/lib/object_factory_writer.rb:64:in `put'
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/traject-2.1.0/lib/traject/indexer.rb:438:in `block (2 levels) in process'
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/traject-2.1.0/lib/traject/thread_pool.rb:110:in `block in maybe_in_thread_pool'
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/concurrent-ruby-0.8.0/lib/concurrent/executor/ruby_thread_pool_worker.rb:62:in `call'
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/concurrent-ruby-0.8.0/lib/concurrent/executor/ruby_thread_pool_worker.rb:62:in `block in run'
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/concurrent-ruby-0.8.0/lib/concurrent/executor/ruby_thread_pool_worker.rb:53:in `loop'
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/concurrent-ruby-0.8.0/lib/concurrent/executor/ruby_thread_pool_worker.rb:53:in `run'
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/concurrent-ruby-0.8.0/lib/concurrent/executor/ruby_thread_pool_executor.rb:255:in `block in create_worker_thread'
```

**Comment by jcoyne** [comment]
The proquest file looks like this:
```xml
  <DISS_restriction>
    <DISS_sales_restriction code="1" remove="10/24/2015"/>
  </DISS_restriction>
  <DISS_repository>
    <DISS_version>2015-02-27 20:47:45</DISS_version>
    <DISS_agreement_decision_date>2015-03-18 11:06:41</DISS_agreement_decision_date>
    <DISS_acceptance>1</DISS_acceptance>
    <DISS_delayed_release>2015-10-24 00:00:00</DISS_delayed_release>
    <DISS_access_option>Open access</DISS_access_option>
  </DISS_repository>
```

**Comment by jcoyne** [comment]
Problem is here:
```
Date.parse('10/24/2015')
ArgumentError: invalid date
```
