### ISSUE TITLE
csv import fails

### ISSUE THREAD

**Issue by acozine** [curationexperts/alexandria-v2#411]
Command:
```
[centos@ip-10-157-142-181 current]$ RAILS_ENV=production script/import_csv /opt/csv_imports/metadata/mss292\(McPeak\)-objects.csv /opt/csv_imports/images/
```
Full stacktrace:
```
Loading environment...
Starting image import...
Note property: note_value => Transferred to Special Collections from UCSB Marine Science Institute, 2011.
Note property: note_type => acquisition
/opt/alex2/shared/bundle/ruby/2.2.0/gems/ldp-0.3.1/lib/ldp/client/methods.rb:108:in `block in check_for_errors': javax.jcr.PathNotFoundException: No node exists at path '/prod/fk/4n/c6/54/Oncorhynchus nerka' in workspace "default" (Ldp::BadRequest)
javax.jcr.PathNotFoundException: No node exists at path '/prod/fk/4n/c6/54/McPeak, Ronald H.' in workspace "default"
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/ldp-0.3.1/lib/ldp/client/methods.rb:106:in `tap'
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/ldp-0.3.1/lib/ldp/client/methods.rb:106:in `check_for_errors'
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/ldp-0.3.1/lib/ldp/client/methods.rb:89:in `put'
	from /opt/alex2/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/caching_connection.rb:24:in `put'
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/ldp-0.3.1/lib/ldp/resource.rb:72:in `create'
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/ldp-0.3.1/lib/ldp/resource/rdf_source.rb:21:in `create'
	from /opt/alex2/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/persistence.rb:147:in `create_record'
	from /opt/alex2/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/indexing.rb:45:in `create_record'
	from /opt/alex2/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/callbacks.rb:237:in `block (2 levels) in create_record'
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:553:in `block (2 levels) in compile'
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:88:in `run_callbacks'
	from /opt/alex2/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/callbacks.rb:237:in `block in create_record'
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:553:in `block (2 levels) in compile'
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:88:in `run_callbacks'
	from /opt/alex2/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/callbacks.rb:236:in `create_record'
	from /opt/alex2/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/persistence.rb:139:in `create_or_update'
	from /opt/alex2/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/persistence.rb:31:in `save!'
	from /opt/alex2/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/validations.rb:56:in `save!'
	from /opt/alex2/releases/20150805172214/lib/importer/factory/object_factory.rb:57:in `block in create'
	from /opt/alex2/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/core.rb:36:in `initialize'
	from /opt/alex2/releases/20150805172214/lib/importer/factory/object_factory.rb:56:in `new'
	from /opt/alex2/releases/20150805172214/lib/importer/factory/object_factory.rb:56:in `create'
	from /opt/alex2/releases/20150805172214/lib/importer/factory/object_factory.rb:15:in `run'
	from /opt/alex2/releases/20150805172214/lib/importer/csv_importer.rb:25:in `create_fedora_objects'
	from /opt/alex2/releases/20150805172214/lib/importer/csv_importer.rb:14:in `block in import_all'
	from /opt/alex2/releases/20150805172214/lib/importer/csv_parser.rb:15:in `block in each'
	from /usr/local/lib/ruby/2.2.0/csv.rb:1739:in `each'
	from /usr/local/lib/ruby/2.2.0/csv.rb:1122:in `block in foreach'
	from /usr/local/lib/ruby/2.2.0/csv.rb:1273:in `open'
	from /usr/local/lib/ruby/2.2.0/csv.rb:1121:in `foreach'
	from /opt/alex2/releases/20150805172214/lib/importer/csv_parser.rb:13:in `each'
	from /opt/alex2/releases/20150805172214/lib/importer/csv_importer.rb:13:in `import_all'
	from script/import_csv:40:in `<main>'
```

**Comment by jcoyne** [comment]
#425 should help give a better error message for this case.

**Comment by acozine** [comment]
I got another bit of test csv that gives me a different error. This one looks like it might be a data modelling question. Command:
```
RAILS_ENV=production script/import_csv /opt/csv_imports/metadata/pamss045\(Couper\)-objects.csv /opt/csv_imports/images/
```
Stacktrace:
```
  Updated collection fk/4q/n6/b3/fk4qn6b38q (PA Mss 45)
  Created image fk/4m/04/9p/fk4m049p7w (PAMSS45-104 - PAMSS45-111)
/opt/alex2/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/attributes.rb:24:in `block in attributes=': TimeSpan does not have an attribute `end_qualifier' (ActiveFedora::UnknownAttributeError)
	from /opt/alex2/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/attributes.rb:23:in `each'
	from /opt/alex2/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/attributes.rb:23:in `attributes='
	from /opt/alex2/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/attributes/serializers.rb:26:in `attributes='
	from /opt/alex2/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/core.rb:34:in `initialize'
	from /opt/alex2/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/reflection.rb:110:in `new'
	from /opt/alex2/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/reflection.rb:110:in `build_association'
	from /opt/alex2/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/associations/association.rb:182:in `build_record'
	from /opt/alex2/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/associations/collection_association.rb:142:in `build'
	from /opt/alex2/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/associations/collection_proxy.rb:233:in `build'
	from /opt/alex2/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/nested_attributes.rb:151:in `block in assign_nested_attributes_for_collection_association'
	from /opt/alex2/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/nested_attributes.rb:147:in `each'
	from /opt/alex2/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/nested_attributes.rb:147:in `assign_nested_attributes_for_collection_association'
	from /opt/alex2/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/nested_attributes.rb:83:in `created_attributes='
	from /opt/alex2/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/attributes.rb:24:in `block in attributes='
	from /opt/alex2/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/attributes.rb:23:in `each'
	from /opt/alex2/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/attributes.rb:23:in `attributes='
	from /opt/alex2/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/attributes/serializers.rb:26:in `attributes='
	from /opt/alex2/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/core.rb:34:in `initialize'
	from /opt/alex2/releases/20150806201720/lib/importer/factory/object_factory.rb:56:in `new'
	from /opt/alex2/releases/20150806201720/lib/importer/factory/object_factory.rb:56:in `create'
	from /opt/alex2/releases/20150806201720/lib/importer/factory/object_factory.rb:15:in `run'
	from /opt/alex2/releases/20150806201720/lib/importer/csv_importer.rb:25:in `create_fedora_objects'
	from /opt/alex2/releases/20150806201720/lib/importer/csv_importer.rb:14:in `block in import_all'
	from /opt/alex2/releases/20150806201720/lib/importer/csv_parser.rb:15:in `block in each'
	from /usr/local/lib/ruby/2.2.0/csv.rb:1739:in `each'
	from /usr/local/lib/ruby/2.2.0/csv.rb:1122:in `block in foreach'
	from /usr/local/lib/ruby/2.2.0/csv.rb:1273:in `open'
	from /usr/local/lib/ruby/2.2.0/csv.rb:1121:in `foreach'
	from /opt/alex2/releases/20150806201720/lib/importer/csv_parser.rb:13:in `each'
	from /opt/alex2/releases/20150806201720/lib/importer/csv_importer.rb:13:in `import_all'
	from script/import_csv:40:in `<main>'
```

**Comment by jcoyne** [comment]
The header named "created_end_qualifier" should be  renamed to "created_finish_qualifier"

**Comment by acozine** [comment]
With the header renamed, the ingest works for all but the last line in the file, which returns another CSV error:
```
/usr/local/lib/ruby/2.2.0/csv.rb:1871:in `block (2 levels) in shift': Unquoted fields do not allow \r or \n (line 6). (CSV::MalformedCSVError)
```
I will talk to UCSB about getting the CSV cleaned up.

**Comment by acozine** [comment]
The `csv` branch of `https://stash.library.ucsb.edu/scm/cms/adrl-dm.git` has a copy of `pamss045\(Couper\)-objects.csv` with correct headers for CSV ingest. I was able to ingest those objects on the DCE sandbox with:
```
RAILS_ENV=production script/import_csv ~/adrl-dm/ingest-ready/pamss045\(Couper\)/pamss045\(Couper\)-objects.csv /opt/csv_imports/images/couper/
```

**Comment by ilessing** [comment]
I merged the ```csv``` branch into ```master```
