### ISSUE TITLE
Traject fails on empty repo

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#439]
**ISSUE**
The first time I run traject on an empty repo, it consistently fails.  When I re-run it, it runs fine.

**STEPS TO REPRODUCE**
```bash
bundle exec rake fedora:clean
bundle exec traject -c traject_config.rb tmp/download_root/marc/all-etds.xml  #fails - see below
bundle exec traject -c traject_config.rb tmp/download_root/marc/all-etds.xml #runs fine
```

**SAMPLE OUTPUT**
```bash
MARKs-MB:alexandria-v2 mark$ bundle exec rake fedora:clean
Cleaning Fedora via 'ActiveFedora.Cleaner.clean!' ...
Finished
MARKs-MB:alexandria-v2 mark$ bundle exec traject -c traject_config.rb tmp/download_root/marc/all-etds.xml 
Performance on MRI may be improved with the concurrent-ruby-ext gem. Please see http://concurrent-ruby.com
/Users/mark/Documents/workspace/_no_backup/RubymineProjects/alexandria-v2/app/models/concerns/relators.rb:2: warning: already initialized constant Metadata::MARCREL
/Users/mark/Documents/workspace/_no_backup/RubymineProjects/alexandria-v2/app/models/concerns/relators.rb:2: warning: previous definition of MARCREL was here
2015-08-08T08:33:49-05:00  INFO traject (2.1.0) executing with: `-c traject_config.rb tmp/download_root/marc/all-etds.xml`
2015-08-08T08:33:49-05:00  INFO Reading from tmp/download_root/marc/all-etds.xml
2015-08-08T08:33:49-05:00  INFO    Indexer with 1 processing threads, reader: Traject::MarcReader and writer: ObjectFactoryWriter
  Created collection fk/4d/f6/xv/fk4df6xv93 (etds)
  Created etd f3/6q/1v/5v/f36q1v5v (003751817)
2015-08-08T08:33:55-05:00 FATAL Traject::CommandLine: Unexpected exception, terminating execution: #<Ldp::HttpError: STATUS: 500 javax.jcr.ItemExistsException: A node definition that allows same name siblings could not be found for the node "{}f3" in workspace "default"
	at org.modeshape.jcr.JcrSession$JcrPreSave.processAfterLocking(JcrSession.java:2422)
	at org.modeshape.jcr.cache.document.WritableSessionCache.runPreSaveAfterLocking(WritableSessionCache.java:530)
	at org.modeshape.jcr.cache.document.WritableSessionCache.save(WritableSessionCache.java:591)
	at org.modeshape.jcr.JcrSession.save(JcrSession.java:1166)
	at org.fcrepo.http.api.FedoraLdp.createOrReplaceObjectRdf(FedoraLdp.java:295)
	at sun.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDis...>
/Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/ldp-0.3.1/lib/ldp/client/methods.rb:108:in `block in check_for_errors': STATUS: 500 javax.jcr.ItemExistsException: A node definition that allows same name siblings could not be found for the node "{}f3" in workspace "default" (Ldp::HttpError)
	at org.modeshape.jcr.JcrSession$JcrPreSave.processAfterLocking(JcrSession.java:2422)
	at org.modeshape.jcr.cache.document.WritableSessionCache.runPreSaveAfterLocking(WritableSessionCache.java:530)
	at org.modeshape.jcr.cache.document.WritableSessionCache.save(WritableSessionCache.java:591)
	at org.modeshape.jcr.JcrSession.save(JcrSession.java:1166)
	at org.fcrepo.http.api.FedoraLdp.createOrReplaceObjectRdf(FedoraLdp.java:295)
	at sun.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDis...
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/ldp-0.3.1/lib/ldp/client/methods.rb:106:in `tap'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/ldp-0.3.1/lib/ldp/client/methods.rb:106:in `check_for_errors'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/ldp-0.3.1/lib/ldp/client/methods.rb:89:in `put'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/caching_connection.rb:24:in `put'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/ldp-0.3.1/lib/ldp/resource.rb:72:in `create'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/ldp-0.3.1/lib/ldp/resource/rdf_source.rb:21:in `create'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/persistence.rb:147:in `create_record'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/indexing.rb:45:in `create_record'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/callbacks.rb:237:in `block (2 levels) in create_record'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:553:in `block (2 levels) in compile'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:88:in `run_callbacks'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/callbacks.rb:237:in `block in create_record'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:553:in `block (2 levels) in compile'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:88:in `run_callbacks'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/callbacks.rb:236:in `create_record'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/persistence.rb:139:in `create_or_update'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/persistence.rb:31:in `save!'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/validations.rb:56:in `save!'
	from /Users/mark/Documents/workspace/_no_backup/RubymineProjects/alexandria-v2/lib/importer/factory/object_factory.rb:57:in `block in create'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/bundler/gems/active_fedora-bd506dc387a7/lib/active_fedora/core.rb:36:in `initialize'
	from /Users/mark/Documents/workspace/_no_backup/RubymineProjects/alexandria-v2/lib/importer/factory/object_factory.rb:56:in `new'
	from /Users/mark/Documents/workspace/_no_backup/RubymineProjects/alexandria-v2/lib/importer/factory/object_factory.rb:56:in `create'
	from /Users/mark/Documents/workspace/_no_backup/RubymineProjects/alexandria-v2/lib/importer/factory/object_factory.rb:15:in `run'
	from /Users/mark/Documents/workspace/_no_backup/RubymineProjects/alexandria-v2/lib/object_factory_writer.rb:59:in `build_object'
	from /Users/mark/Documents/workspace/_no_backup/RubymineProjects/alexandria-v2/lib/object_factory_writer.rb:53:in `put'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/traject-2.1.0/lib/traject/indexer.rb:438:in `block (2 levels) in process'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/traject-2.1.0/lib/traject/thread_pool.rb:110:in `block in maybe_in_thread_pool'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/concurrent-ruby-0.8.0/lib/concurrent/executor/ruby_thread_pool_worker.rb:62:in `call'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/concurrent-ruby-0.8.0/lib/concurrent/executor/ruby_thread_pool_worker.rb:62:in `block in run'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/concurrent-ruby-0.8.0/lib/concurrent/executor/ruby_thread_pool_worker.rb:53:in `loop'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/concurrent-ruby-0.8.0/lib/concurrent/executor/ruby_thread_pool_worker.rb:53:in `run'
	from /Users/mark/.rvm/gems/ruby-2.2.2@alexandria/gems/concurrent-ruby-0.8.0/lib/concurrent/executor/ruby_thread_pool_executor.rb:255:in `block in create_worker_thread'
MARKs-MB:alexandria-v2 mark$ bundle exec traject -c traject_config.rb tmp/download_root/marc/all-etds.xml 
Performance on MRI may be improved with the concurrent-ruby-ext gem. Please see http://concurrent-ruby.com
/Users/mark/Documents/workspace/_no_backup/RubymineProjects/alexandria-v2/app/models/concerns/relators.rb:2: warning: already initialized constant Metadata::MARCREL
/Users/mark/Documents/workspace/_no_backup/RubymineProjects/alexandria-v2/app/models/concerns/relators.rb:2: warning: previous definition of MARCREL was here
2015-08-08T08:35:16-05:00  INFO traject (2.1.0) executing with: `-c traject_config.rb tmp/download_root/marc/all-etds.xml`
2015-08-08T08:35:16-05:00  INFO Reading from tmp/download_root/marc/all-etds.xml
2015-08-08T08:35:16-05:00  INFO    Indexer with 1 processing threads, reader: Traject::MarcReader and writer: ObjectFactoryWriter
  Updated collection fk/4d/f6/xv/fk4df6xv93 (etds)
  Updated etd f3/6q/1v/5v/f36q1v5v (003751817)
  Updated collection fk/4d/f6/xv/fk4df6xv93 (etds)
  Created etd f3/n0/14/n7/f3n014n7 (003683909)
  Updated collection fk/4d/f6/xv/fk4df6xv93 (etds)
  Created etd f3/2z/13/fh/f32z13fh (003751818)

. . .   and so on  . . . 
```

**Comment by mark-dce** [comment]
Marking this low-priority even though it's a bug.  If we can diagnose and fix it in <2 hours, it would be great to take care of; otherwise, it only occurs on totally empty repos and there's an easy work-around of just re-running the import a second time (after which the repo isn't empty and the error doesn't seem to reoccur)

**Comment by jcoyne** [comment]
See: https://github.com/fcrepo4/fcrepo4/issues/880
