### ISSUE TITLE
CSV ingest with "type" field fails

### ISSUE THREAD

**Issue by acozine** [curationexperts/alexandria-v2#529]
I amalgamated the collection metadata and the object metadata for the McPeak photographs we have into a single CSV file (/data/metadata-mcpeak/collection-and-objects.csv). I added a row for the collection metadata to the object metadata file and added four columns:
- [ ] "type" as the first field, with values of "Collection" and "Image"
- [ ] "lc_subject_type" to allow creating Subject local authorities
- [ ] "photographer_type" to allow creating Person local authorities
- [ ] "alternative" as the last field (the only field from the collection level metadata that didn't exist in the object metadata file).
When I try to ingest the collection and objects now, I get:
```
[deploy@ip-10-0-0-120 current]$ RAILS_ENV=production bin/ingest-csv /data/metadata-mcpeak/collection-and-objects.csv /data/objects-mcpeak
Loading environment...
Starting import...
Note property: note_value => From the Ronald H. McPeak underwater and coastal California photographs, Mss 292.
Note property: note_type => original
/opt/alexandria-v2/shared/bundle/ruby/2.2.0/gems/active-fedora-9.7.0/lib/active_fedora/attributes.rb:24:in `block in attributes=': Collection does not have an attribute `type' (ActiveFedora::UnknownAttributeError)
	from /opt/alexandria-v2/shared/bundle/ruby/2.2.0/gems/active-fedora-9.7.0/lib/active_fedora/attributes.rb:23:in `each'
	from /opt/alexandria-v2/shared/bundle/ruby/2.2.0/gems/active-fedora-9.7.0/lib/active_fedora/attributes.rb:23:in `attributes='
	from /opt/alexandria-v2/shared/bundle/ruby/2.2.0/gems/active-fedora-9.7.0/lib/active_fedora/attributes/serializers.rb:24:in `attributes='
	from /opt/alexandria-v2/shared/bundle/ruby/2.2.0/gems/active-fedora-9.7.0/lib/active_fedora/core.rb:34:in `initialize'
	from /opt/alexandria-v2/releases/20160127204527/lib/importer/factory/object_factory.rb:68:in `new'
	from /opt/alexandria-v2/releases/20160127204527/lib/importer/factory/object_factory.rb:68:in `create'
	from /opt/alexandria-v2/releases/20160127204527/lib/importer/factory/object_factory.rb:20:in `block in run'
	from /opt/alexandria-v2/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/notifications.rb:164:in `block in instrument'
	from /opt/alexandria-v2/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	from /opt/alexandria-v2/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/notifications.rb:164:in `instrument'
	from /opt/alexandria-v2/releases/20160127204527/lib/importer/factory/object_factory.rb:18:in `run'
	from /opt/alexandria-v2/releases/20160127204527/lib/importer/csv_importer.rb:33:in `create_fedora_objects'
	from /opt/alexandria-v2/releases/20160127204527/lib/importer/csv_importer.rb:17:in `block in import_all'
	from /opt/alexandria-v2/releases/20160127204527/lib/importer/csv_parser.rb:15:in `block in each'
	from /usr/local/lib/ruby/2.2.0/csv.rb:1739:in `each'
	from /usr/local/lib/ruby/2.2.0/csv.rb:1122:in `block in foreach'
	from /usr/local/lib/ruby/2.2.0/csv.rb:1273:in `open'
	from /usr/local/lib/ruby/2.2.0/csv.rb:1121:in `foreach'
	from /opt/alexandria-v2/releases/20160127204527/lib/importer/csv_parser.rb:13:in `each'
	from /opt/alexandria-v2/releases/20160127204527/lib/importer/csv_importer.rb:16:in `import_all'
	from bin/ingest-csv:37:in `<main>'
```

**Comment by acozine** [comment]
I changed use_restrictions to restrictions and changed the header on an empty column from form_of_work to work_type. I can't see how that would create an issue.

**Comment by jcoyne** [comment]
Hmm, I now see the same error running:

```
bin/ingest-csv spec/fixtures/csv/pamss045_with_type.csv
```
