### ISSUE TITLE
"Key not found" error when ingesting cylinders

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria-v2#633]
```
2016-03-02T03:38:18+00:00 ERROR Unexpected error on record id `004110610/f36m3682` at file position 9
    while executing (to_field contributors at lib/traject/audio_config.rb:50)
    Exception: KeyError: key not found: "performer."
    /opt/alexandria-v2/releases/20160302033458/lib/traject/extract_contributors.rb:70:in `fetch'

2016-03-02T03:38:18+00:00 FATAL Traject::CommandLine: Unexpected exception, terminating execution: #<KeyError: key not found: "performer.">
/opt/alexandria-v2/releases/20160302033458/lib/traject/extract_contributors.rb:70:in `fetch': key not found: "performer." (KeyError)
	from /opt/alexandria-v2/releases/20160302033458/lib/traject/extract_contributors.rb:70:in `block in roles_for'
	from /opt/alexandria-v2/releases/20160302033458/lib/traject/extract_contributors.rb:70:in `map'
	from /opt/alexandria-v2/releases/20160302033458/lib/traject/extract_contributors.rb:70:in `roles_for'
	from /opt/alexandria-v2/releases/20160302033458/lib/traject/extract_contributors.rb:49:in `block (2 levels) in extract_contributors'
	from /opt/alexandria-v2/releases/20160302033458/lib/traject/extract_contributors.rb:48:in `each'
	from /opt/alexandria-v2/releases/20160302033458/lib/traject/extract_contributors.rb:48:in `block in extract_contributors'
	from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/traject-2.3.0/lib/traject/indexer/step.rb:142:in `execute'
	from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/traject-2.3.0/lib/traject/indexer.rb:347:in `block (2 levels) in map_to_context!'
	from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/traject-2.3.0/lib/traject/indexer.rb:401:in `log_mapping_errors'
	from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/traject-2.3.0/lib/traject/indexer.rb:346:in `block in map_to_context!'
	from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/traject-2.3.0/lib/traject/indexer.rb:340:in `each'
	from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/traject-2.3.0/lib/traject/indexer.rb:340:in `map_to_context!'
	from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/traject-2.3.0/lib/traject/indexer.rb:475:in `block (2 levels) in process'
	from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/traject-2.3.0/lib/traject/thread_pool.rb:114:in `maybe_in_thread_pool'
	from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/traject-2.3.0/lib/traject/indexer.rb:474:in `block in process'
	from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/marc-1.0.0/lib/marc/xml_parsers.rb:37:in `yield_record'
	from /opt/alexandria-v2/shared/bundle/ruby/2.3.0/gems/marc-1.0.0/lib/marc/xml_parsers.rb:72:in `end_element_namespace'
```

**Comment by jcoyne** [comment]
I suspect it's choking on this:
```xml
  <datafield tag="700" ind1="1" ind2=" ">
    <subfield code="a">Milner, David,</subfield>
    <subfield code="e">performer.</subfield>
  </datafield>
```

@val99erie do you know what this means?  Should it be using `trim_punctuation: true` ?
